In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split

In [9]:
from sklearn.preprocessing import LabelEncoder
df=sns.load_dataset('iris')

data=pd.read_csv(r'D:\Git\Personal\PGA43_ML\ML Session 7\Inclass\data\online_gaming_behavior_dataset (1).csv')
le=LabelEncoder()
for col in data.select_dtypes(include=["object"]).columns:
    data[col]=le.fit_transform(data[col]).astype(str)

df['species_n']=le.fit_transform(df['species']).astype(str)
df

     sepal_length  sepal_width  petal_length  petal_width    species species_n
0             5.1          3.5           1.4          0.2     setosa         0
1             4.9          3.0           1.4          0.2     setosa         0
2             4.7          3.2           1.3          0.2     setosa         0
3             4.6          3.1           1.5          0.2     setosa         0
4             5.0          3.6           1.4          0.2     setosa         0
..            ...          ...           ...          ...        ...       ...
145           6.7          3.0           5.2          2.3  virginica         2
146           6.3          2.5           5.0          1.9  virginica         2
147           6.5          3.0           5.2          2.0  virginica         2
148           6.2          3.4           5.4          2.3  virginica         2
149           5.9          3.0           5.1          1.8  virginica         2

[150 rows x 6 columns]

In [6]:
print(data.head())
print("Information about the dataset:")
print(data.info())
print("Description of the dataset:")
print(data.describe(include='all'))
print("Checking for missing values:")
print(data.isnull().sum())
print("Checking for duplicate rows:")
print(data.duplicated().sum())
print("Checking for unique values in each column:")
for column in data.columns:
    print(f"{column}: {data[column].nunique()} unique values")
    print(f"{column}: {data[column].unique()} unique values")

print("Shape of the dataset:", data.shape)

   PlayerID  Age Gender Location GameGenre  PlayTimeHours  InGamePurchases  \
0      9000   43      1        2         4      16.271119                0
1      9001   29      0        3         4       5.525961                0
2      9002   22      0        3         3       8.223755                0
3      9003   35      1        3         0       5.265351                1
4      9004   33      1        1         0      15.531945                0

  GameDifficulty  SessionsPerWeek  AvgSessionDurationMinutes  PlayerLevel  \
0              2                6                        108           79
1              2                5                        144           11
2              0               16                        142           35
3              0                9                         85           57
4              2                2                        131           95

   AchievementsUnlocked EngagementLevel
0                    25               2
1                    10               2
2                    41               0
3                    47               2
4                    37               2
Information about the dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40034 entries, 0 to 40033
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   PlayerID                   40034 non-null  int64
 1   Age                        40034 non-null  int64
 2   Gender                     40034 non-null  object
 3   Location                   40034 non-null  object
 4   GameGenre                  40034 non-null  object
 5   PlayTimeHours              40034 non-null  float64
 6   InGamePurchases            40034 non-null  int64
 7   GameDifficulty             40034 non-null  object
 8   SessionsPerWeek            40034 non-null  int64
 9   AvgSessionDurationMinutes  40034 non-null  int64
 10  PlayerLevel                40034 non-null  int64
 11  AchievementsUnlocked       40034 non-null  int64
 12  EngagementLevel            40034 non-null  object
dtypes: float64(1), int64(7), object(5)
memory usage: 4.0+ MB
None
Description of the dataset:
            PlayerID           Age Gender Location GameGenre  PlayTimeHours  \
count   40034.000000  40034.000000  40034    40034     40034   40034.000000
unique           NaN           NaN      2        4         5            NaN
top              NaN           NaN      1        3         3            NaN
freq             NaN           NaN  23959    16000      8048            NaN
mean    29016.500000     31.992531    NaN      NaN       NaN      12.024365
std     11556.964675     10.043227    NaN      NaN       NaN       6.914638
min      9000.000000     15.000000    NaN      NaN       NaN       0.000115
25%     19008.250000     23.000000    NaN      NaN       NaN       6.067501
50%     29016.500000     32.000000    NaN      NaN       NaN      12.008002
75%     39024.750000     41.000000    NaN      NaN       NaN      17.963831
max     49033.000000     49.000000    NaN      NaN       NaN      23.999592

        InGamePurchases GameDifficulty  SessionsPerWeek  \
count      40034.000000          40034     40034.000000
unique              NaN              3              NaN
top                 NaN              0              NaN
freq                NaN          20015              NaN
mean           0.200854            NaN         9.471774
std            0.400644            NaN         5.763667
min            0.000000            NaN         0.000000
25%            0.000000            NaN         4.000000
50%            0.000000            NaN         9.000000
75%            0.000000            NaN        14.000000
max            1.000000            NaN        19.000000

        AvgSessionDurationMinutes   PlayerLevel  AchievementsUnlocked  \
count                40034.000000  40034.000000          40034.000000
unique                        NaN           NaN                   NaN
top                           NaN           NaN                   NaN
freq                          NaN           NaN                   NaN
mean                    94.792252     49.655568             24.526477
std                     49.011375     28.588379             14.430726
min                     10.000000      1.000000              0.000000
25%                     52.000000     25.000000             12.000000
50%                     95.000000     49.000000             25.000000
75%                    137.000000     74.000000             37.000000
max                    179.000000     99.000000             49.000000

       EngagementLevel
count            40034
unique               3
top                  2
freq             19374
mean               NaN
std                NaN
min                NaN
25%                NaN
50%                NaN
75%                NaN
max                NaN
Checking for missing values:
PlayerID                     0
Age                          0
Gender                       0
Location                     0
GameGenre                    0
PlayTimeHours                0
InGamePurchases              0
GameDifficulty               0
SessionsPerWeek              0
AvgSessionDurationMinutes    0
PlayerLevel                  0
AchievementsUnlocked         0
EngagementLevel              0
dtype: int64
Checking for duplicate rows:
0
Checking for unique values in each column:
PlayerID: 40034 unique values
PlayerID: [ 9000  9001  9002 ... 49031 49032 49033] unique values
Age: 35 unique values
Age: [43 29 22 35 33 37 25 38 17 36 16 44 47 26 39 41 42 30 21 23 32 18 28 40
 34 49 31 20 48 24 45 15 19 27 46] unique values
Gender: 2 unique values
Gender: ['1' '0'] unique values
Location: 4 unique values
Location: ['2' '3' '1' '0'] unique values
GameGenre: 5 unique values
GameGenre: ['4' '3' '0' '1' '2'] unique values
PlayTimeHours: 40034 unique values
PlayTimeHours: [16.27111876  5.52596138  8.22375524 ...  0.24005688 14.01781798
 10.08380358] unique values
InGamePurchases: 2 unique values
InGamePurchases: [0 1] unique values
GameDifficulty: 3 unique values
GameDifficulty: ['2' '0' '1'] unique values
SessionsPerWeek: 20 unique values
SessionsPerWeek: [ 6  5 16  9  2  1 10 13  8  0  3  4 18 14 12 19 17 11 15  7] unique values
AvgSessionDurationMinutes: 170 unique values
AvgSessionDurationMinutes: [108 144 142  85 131  81  50  48 101  95 124  18 156  41 154 135  56 177
 159 120 117 161  82 118  57 155  67  70 127 166  28  61 112 116  43 151
  68 115 149  65 176  31  77  94 146  45 134 171  46 139  36 148 153 138
 140  16  49  30 167  79 111 109 106  29  83  14  34 102 122 147 107  73
  12  99  32 126  84  55  93  40  33  91  24  72  96 121  60 145  51  69
  75  17  62 157  78  21  42 103  52 132 105  27  19  39  92 179 164  90
 110 133  98  89  80  47  20  10 152 128  71 175  88 125  74 168  76 169
 172 170 150  23  87 160  26  63 174 165  66 104  44 158 162  59 178  86
  64 114 173 113 163  35 123  53 119  58 136  37  54  97 130  25 100 129
 143  38  13  11  15  22 141 137] unique values
PlayerLevel: 99 unique values
PlayerLevel: [79 11 35 57 95 74 13 27 23 99 14 62 52 33 98 58 77 21 34 36 81 40  1 71
 59  2 85 50 48 24 26 93 76 88 10 45 73 51 31 22 19 64  6  8 20 46 38 80
  3 72 29 12 91  9 15  4 89 78 61 54 65 53 56 75  5 42 69 49 92 96 82 87
 60 39 66 55 32  7 83 67 16 84 68 94 44 30 47 25 90 17 63 28 97 86 37 43
 70 41 18] unique values
AchievementsUnlocked: 50 unique values
AchievementsUnlocked: [25 10 41 47 37 22  2 23 36 12 31 32  1 24  4  9 30 33  5 19  7 26 18 11
 48 42 17  0 44 29 35 39 34 46 43 49 38 13 21 16 40 15 28 14 45 20 27  3
  8  6] unique values
EngagementLevel: 3 unique values
EngagementLevel: ['2' '0' '1'] unique values
Shape of the dataset: (40034, 13)

In [7]:
data.groupby(['GameGenre', 'SessionsPerWeek'])['PlayerID'].count()

GameGenre  SessionsPerWeek
0          0                  408
           1                  392
           2                  390
           3                  413
           4                  440
                             ...
4          15                 427
           16                 433
           17                 391
           18                 412
           19                 397
Name: PlayerID, Length: 100, dtype: int64

In [8]:
for i in data['SessionsPerWeek'].unique()   :
    print(f"SessionsPerWeek: {i}")
    print(data[data['SessionsPerWeek'] == i].groupby(['GameGenre'])['PlayerID'].count())

SessionsPerWeek: 6
GameGenre
0    428
1    428
2    367
3    393
4    377
Name: PlayerID, dtype: int64
SessionsPerWeek: 5
GameGenre
0    385
1    409
2    401
3    410
4    430
Name: PlayerID, dtype: int64
SessionsPerWeek: 16
GameGenre
0    394
1    360
2    410
3    412
4    433
Name: PlayerID, dtype: int64
SessionsPerWeek: 9
GameGenre
0    399
1    422
2    388
3    382
4    383
Name: PlayerID, dtype: int64
SessionsPerWeek: 2
GameGenre
0    390
1    387
2    410
3    427
4    404
Name: PlayerID, dtype: int64
SessionsPerWeek: 1
GameGenre
0    392
1    411
2    402
3    396
4    379
Name: PlayerID, dtype: int64
SessionsPerWeek: 10
GameGenre
0    427
1    403
2    377
3    411
4    338
Name: PlayerID, dtype: int64
SessionsPerWeek: 13
GameGenre
0    395
1    377
2    405
3    415
4    391
Name: PlayerID, dtype: int64
SessionsPerWeek: 8
GameGenre
0    356
1    406
2    392
3    392
4    417
Name: PlayerID, dtype: int64
SessionsPerWeek: 0
GameGenre
0    408
1    385
2    429
3    366
4    379
Name: PlayerID, dtype: int64
SessionsPerWeek: 3
GameGenre
0    413
1    395
2    419
3    401
4    391
Name: PlayerID, dtype: int64
SessionsPerWeek: 4
GameGenre
0    440
1    408
2    404
3    427
4    412
Name: PlayerID, dtype: int64
SessionsPerWeek: 18
GameGenre
0    412
1    408
2    366
3    400
4    412
Name: PlayerID, dtype: int64
SessionsPerWeek: 14
GameGenre
0    395
1    407
2    385
3    407
4    364
Name: PlayerID, dtype: int64
SessionsPerWeek: 12
GameGenre
0    403
1    401
2    422
3    416
4    410
Name: PlayerID, dtype: int64
SessionsPerWeek: 19
GameGenre
0    419
1    371
2    419
3    426
4    397
Name: PlayerID, dtype: int64
SessionsPerWeek: 17
GameGenre
0    408
1    395
2    407
3    357
4    391
Name: PlayerID, dtype: int64
SessionsPerWeek: 11
GameGenre
0    391
1    365
2    386
3    398
4    422
Name: PlayerID, dtype: int64
SessionsPerWeek: 15
GameGenre
0    359
1    389
2    389
3    385
4    427
Name: PlayerID, dtype: int64
SessionsPerWeek: 7
GameGenre
0    425
1    425
2    405
3    427
4    455
Name: PlayerID, dtype: int64

In [9]:
x=data.drop(['PlayerID','EngagementLevel'],axis=1)
print(x)

       Age Gender Location GameGenre  PlayTimeHours  InGamePurchases  \
0       43      1        2         4      16.271119                0
1       29      0        3         4       5.525961                0
2       22      0        3         3       8.223755                0
3       35      1        3         0       5.265351                1
4       33      1        1         0      15.531945                0
...    ...    ...      ...       ...            ...              ...
40029   32      1        3         4      20.619662                0
40030   44      0        2         2      13.539280                0
40031   15      0        3         1       0.240057                1
40032   34      1        3         3      14.017818                1
40033   19      1        3         3      10.083804                0

      GameDifficulty  SessionsPerWeek  AvgSessionDurationMinutes  PlayerLevel  \
0                  2                6                        108           79
1                  2                5                        144           11
2                  0               16                        142           35
3                  0                9                         85           57
4                  2                2                        131           95
...              ...              ...                        ...          ...
40029              0                4                         75           85
40030              1               19                        114           71
40031              0               10                        176           29
40032              2                3                        128           70
40033              0               13                         84           72

       AchievementsUnlocked
0                        25
1                        10
2                        41
3                        47
4                        37
...                     ...
40029                    14
40030                    27
40031                     1
40032                    10
40033                    39

[40034 rows x 11 columns]

In [10]:
y=data['EngagementLevel']
y

0        2
1        2
2        0
3        2
4        2
        ..
40029    2
40030    0
40031    0
40032    2
40033    2
Name: EngagementLevel, Length: 40034, dtype: object

In [11]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3,random_state=42)
print(xtest.shape)
print(ytest.shape)
print(ytrain)
print(xtrain)

(12011, 11)
(12011,)
15851    0
38470    2
11469    2
6713     1
14054    1
        ..
6265     1
11284    0
38158    0
860      0
15795    1
Name: EngagementLevel, Length: 28023, dtype: object
       Age Gender Location GameGenre  PlayTimeHours  InGamePurchases  \
15851   39      1        1         3      22.797054                0
38470   43      0        1         0       3.423246                0
11469   47      1        3         2       2.044750                1
6713    35      1        1         1      21.349632                0
14054   24      0        0         3      15.118617                0
...    ...    ...      ...       ...            ...              ...
6265    49      1        1         0      23.372697                0
11284   45      1        1         0      15.949695                0
38158   36      1        0         3       1.981719                1
860     22      0        3         4      22.617087                0
15795   40      1        3         2       6.343174                0

      GameDifficulty  SessionsPerWeek  AvgSessionDurationMinutes  PlayerLevel  \
15851              0               15                        171           33
38470              0               10                         88           97
11469              0               11                         37           30
6713               1                0                         88           78
14054              2                0                        174           43
...              ...              ...                        ...          ...
6265               2                3                         44            4
11284              0               10                        170           29
38158              0               12                        135           67
860                0               13                        114           14
15795              0                4                         65           58

       AchievementsUnlocked
15851                    35
38470                    27
11469                     0
6713                     25
14054                    15
...                     ...
6265                     17
11284                    27
38158                    33
860                      12
15795                    18

[28023 rows x 11 columns]

In [12]:
train=pd.concat([xtrain,ytrain],axis=1)
train

,Age,Gender,Location,GameGenre,PlayTimeHours,InGamePurchases,GameDifficulty,SessionsPerWeek,AvgSessionDurationMinutes,PlayerLevel,AchievementsUnlocked,EngagementLevel
15851,39,1,1,3,22.797054,0,0,15,171,33,35,0
38470,43,0,1,0,3.423246,0,0,10,88,97,27,2
11469,47,1,3,2,2.044750,1,0,11,37,30,0,2
6713,35,1,1,1,21.349632,0,1,0,88,78,25,1
14054,24,0,0,3,15.118617,0,2,0,174,43,15,1
...,...,...,...,...,...,...,...,...,...,...,...,...
6265,49,1,1,0,23.372697,0,2,3,44,4,17,1
11284,45,1,1,0,15.949695,0,0,10,170,29,27,0
38158,36,1,0,3,1.981719,1,0,12,135,67,33,0
860,22,0,3,4,22.617087,0,0,13,114,14,12,0
15795,40,1,3,2,6.343174,0,0,4,65,58,18,1

In [13]:
test=pd.concat([xtest,ytest],axis=1)
test

,Age,Gender,Location,GameGenre,PlayTimeHours,InGamePurchases,GameDifficulty,SessionsPerWeek,AvgSessionDurationMinutes,PlayerLevel,AchievementsUnlocked,EngagementLevel
34667,49,1,2,0,3.326911,1,2,16,63,43,6,2
22227,29,0,3,0,19.626462,0,1,10,99,48,11,2
24899,32,1,0,3,23.322086,0,2,11,17,12,34,2
35415,49,1,0,0,10.348791,0,2,7,149,44,38,2
21440,48,0,2,2,6.238742,0,0,10,127,14,4,2
...,...,...,...,...,...,...,...,...,...,...,...,...
26873,24,1,1,3,18.941348,0,2,12,93,49,22,2
24797,39,1,3,2,16.331087,0,1,2,82,8,17,1
24023,48,0,3,3,5.659405,0,0,12,45,55,16,2
38472,15,0,3,4,5.947767,0,0,6,63,17,4,2
6373,47,1,3,4,15.488333,0,0,16,55,14,26,2

In [14]:
train.to_csv('train.csv',index=False)
test.to_csv("test.csv",index=False)

In [15]:
data.groupby('EngagementLevel').count()

,PlayerID,Age,Gender,Location,GameGenre,PlayTimeHours,InGamePurchases,GameDifficulty,SessionsPerWeek,AvgSessionDurationMinutes,PlayerLevel,AchievementsUnlocked
EngagementLevel,,,,,,,,,,,,
0,10336,10336,10336,10336,10336,10336,10336,10336,10336,10336,10336,10336
1,10324,10324,10324,10324,10324,10324,10324,10324,10324,10324,10324,10324
2,19374,19374,19374,19374,19374,19374,19374,19374,19374,19374,19374,19374

In [16]:
train.groupby('EngagementLevel').count()

,Age,Gender,Location,GameGenre,PlayTimeHours,InGamePurchases,GameDifficulty,SessionsPerWeek,AvgSessionDurationMinutes,PlayerLevel,AchievementsUnlocked
EngagementLevel,,,,,,,,,,,
0,7204,7204,7204,7204,7204,7204,7204,7204,7204,7204,7204
1,7255,7255,7255,7255,7255,7255,7255,7255,7255,7255,7255
2,13564,13564,13564,13564,13564,13564,13564,13564,13564,13564,13564

In [17]:
test.groupby('EngagementLevel').count()

,Age,Gender,Location,GameGenre,PlayTimeHours,InGamePurchases,GameDifficulty,SessionsPerWeek,AvgSessionDurationMinutes,PlayerLevel,AchievementsUnlocked
EngagementLevel,,,,,,,,,,,
0,3132,3132,3132,3132,3132,3132,3132,3132,3132,3132,3132
1,3069,3069,3069,3069,3069,3069,3069,3069,3069,3069,3069
2,5810,5810,5810,5810,5810,5810,5810,5810,5810,5810,5810